
import React from 'react';
import { useFranchiseContext, useUIContext } from '../hooks';
import { Building } from '../components/ui/icons';
import { Stadium } from '../types';

const FacilityCard: React.FC<{
    title: string;
    level: number;
    description: string;
    onUpgrade: () => void;
    cost: number;
    canAfford: boolean;
}> = ({ title, level, description, onUpgrade, cost, canAfford }) => (
    <div className="bg-gray-700/50 p-4 rounded-lg">
        <h3 className="font-bold text-lg text-white">{title}</h3>
        <p className="text-sm text-gray-400 mb-2">Current Level: <span className="font-semibold text-teal-400">{level}</span></p>
        <p className="text-xs text-gray-400 min-h-[40px]">{description}</p>
        <div className="mt-4 flex justify-between items-center">
            <span className="text-sm font-semibold text-gray-300">Upgrade Cost: ${cost.toLocaleString()}</span>
            <button
                onClick={onUpgrade}
                disabled={!canAfford}
                className="px-3 py-1 bg-green-600 hover:bg-green-500 text-white font-bold rounded-md text-sm disabled:bg-gray-600 disabled:cursor-not-allowed"
            >
                Upgrade
            </button>
        </div>
    </div>
);


const StadiumPage: React.FC = () => {
    const { franchiseState, dispatch } = useFranchiseContext();
    const { uiState } = useUIContext();
    const { stadium, finances } = franchiseState;
    const { activeTeamContext } = uiState;
    const activeTeam = activeTeamContext === 'away' ? 'away' : 'home';
    const teamStadium = stadium[activeTeam];
    const teamFinances = finances[activeTeam];

    const handleUpgrade = (facility: keyof Omit<Stadium, 'capacity'>) => {
        dispatch({ type: 'UPGRADE_STADIUM_FACILITY', payload: { team: activeTeam, facility } });
    };

    return (
        <div className="w-full h-full flex items-center justify-center p-4 bg-gray-900">
            <div 
                className="relative bg-gray-800 rounded-lg shadow-2xl w-full max-w-2xl border border-gray-700/50 flex flex-col animate-fade-in-scale max-h-[90vh]"
            >
                <div className="flex justify-between items-center p-4 border-b border-gray-700">
                    <h2 className="text-xl font-bold text-teal-400 flex items-center">
                        <Building className="w-5 h-5 mr-3" />
                        Stadium & Facilities ({activeTeam})
                    </h2>
                </div>
                
                <div className="p-6 overflow-y-auto space-y-4">
                     <div className="text-center bg-gray-900/50 p-4 rounded-lg">
                        <p className="text-sm text-gray-400">Stadium Capacity</p>
                        <p className="text-3xl font-bold text-white">{teamStadium.capacity.toLocaleString()}</p>
                        <p className="text-xs text-gray-500">Increases matchday income. (Upgrades unavailable)</p>
                     </div>
                     <FacilityCard 
                        title="Training Facilities"
                        level={teamStadium.trainingFacilitiesLevel}
                        description="Improves the rate of player development and attribute growth during training."
                        cost={teamStadium.trainingFacilitiesLevel * 5000000}
                        canAfford={teamFinances.transferBudget >= teamStadium.trainingFacilitiesLevel * 5000000}
                        onUpgrade={() => handleUpgrade('trainingFacilitiesLevel')}
                    />
                     <FacilityCard 
                        title="Youth Facilities"
                        level={teamStadium.youthFacilitiesLevel}
                        description="Increases the quality and potential of prospects generated by the youth academy."
                        cost={teamStadium.youthFacilitiesLevel * 3000000}
                        canAfford={teamFinances.transferBudget >= teamStadium.youthFacilitiesLevel * 3000000}
                        onUpgrade={() => handleUpgrade('youthFacilitiesLevel')}
                    />
                </div>
            </div>
        </div>
    );
};

export default StadiumPage;